asn1crypto==0.24.0
attrs==17.4.0
click==7.1.2
convertdate==2.2.0
cryptography==2.1.4
decorator==4.1.2
Django==1.11.29
docutils==0.16
enum34==1.1.6
Flask==1.1.2
Flask-Login==0.5.0
Flask-SQLAlchemy==2.4.1
Flask-WTF==0.14.3
funcsigs==1.0.2
holidays==0.10.2
idna==2.6
ipaddress==1.0.17
itsdangerous==1.1.0
Jinja2==2.11.2
keyring==10.6.0
keyrings.alt==3.0
korean-lunar-calendar==0.2.1
MarkupSafe==1.1.1
numpy==1.16.6
olefile==0.45.1
Pillow==5.1.0
pluggy==0.6.0
py==1.5.2
pycrypto==2.6.1
pygobject==3.26.1
PyMeeus==0.3.7
pytest==3.3.2
python-dateutil==2.8.1
pytz==2020.1
pyxdg==0.25
scipy==1.2.3
SecretStorage==2.3.1
six==1.14.0
SQLAlchemy==1.3.15
statistics==1.0.3.5
Werkzeug==1.0.1
WTForms==2.3.1
 
